### ISSUE TITLE
Cannot get persistent fly working

### ISSUE THREAD

**Issue by Antmanofgod** [Spazzinq/FlightControl#55]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *(if not just an error)*
 
... I cannot get persistent fly working, in other words if a player is flying before they log out, they would like to be flying when they log back in, but instead, they appear on the ground.
 
**Error** *(if there's an error, use gist to paste it)*
 ...
 
**Configuration** *(use gist to paste)*
 ...
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 
... No

**Server Version** *(e.g. Paper Spigot 1.16.1)*
 ...

**Comment by Spazzinq** [comment]
This behavior is not caused by FlightControl, but rather other plugins that you have installed. Vanilla Minecraft does not update the flight status, and it is not FlightControl disabling your flight (just to enable it again seconds later).

I've contacted you about ways to work around this problem (notably granting `essentials.fly.safelogin` and `essentials.fly`).
